### ISSUE TITLE
git bash

### ISSUE THREAD

**Issue by ricardomga** [neilpa/cmd-colors-solarized#12]
didn't work at the git bash

**Comment by user004** [comment]
I also got the regedit installed and working on Command Prompt, but not Bash.

**Comment by shurane** [comment]
Git Bash uses `mintty`, not the terminal that `cmd.exe` uses. You'll have to look at the color schemes on Mintty's [wiki](https://github.com/mintty/mintty/wiki/Tips#using-colour-schemes-themes).

**Comment by neilpa** [comment]
See my response in #1 about palette mapping differences between *nix and windows.
