### ISSUE TITLE
Powershell arguments are coloured too dark

### ISSUE THREAD

**Issue by dhensby** [neilpa/cmd-colors-solarized#24]
On a clean install of Windows 10 Creators Edition I've installed the solarized-dark theme.

Powershell changes the colour of typed commands based on their context (if they are parameters, for example).

For parameters (words starting with a `-` the colour used is too close to the background colour making them practically invisible:

Here's an example:
![](https://dl.dropboxusercontent.com/s/55pl17fuj7q3jc0/powershell_2017-06-30_13-29-33_FnyV4QE8aZ.png)

They typed command here is `Set-PSReadlineOption -TokenKind parameter -ForegroundColor white`, which happens to be a temporary fix

**Comment by rbeesley** [comment]
It looks like it is showing base02 when it should be showing base01. You added the profile script I assume? You'll see that there is a line which reads: `$options.ParameterForegroundColor = 'DarkGreen'`. You'll see that this matches the output for base01. It would seem as though not all of the colors are set correctly.

**Comment by letmaik** [comment]
I had the same problem. I followed the new installation instructions and the problem is gone now.

**Comment by dhensby** [comment]
thanks for the reply and sorry for my delay in responding. I've followed the install instructions again and I think the problem was I was placing the scripts in my Documents folder that lived in OneDrive instead of in my "local" Documents folder.

I did also have to run `Set-ExecutionPolicy -ExecutionPolicy RemoteSigned` in powershell with elevated permissions to get my profile script to run - I couldn't see this mentioned in the installation instructions.

Thanks :)

**Comment by rbeesley** [comment]
@dhensby, you should **not** have to change your Execution Policy to run the batch file. The batch file will launch PowerShell and run the script in Bypass mode specifically so that users do not change the default execution policy. I'd advise you to set it back to Restricted since that is the secure default PowerShell ships with.

**Comment by dhensby** [comment]
@rbeesley thanks - I've set the policy back to restricted but now see:

```
Windows PowerShell
Copyright (C) 2016 Microsoft Corporation. All rights reserved.

. : File C:\Users\[redacted]\Documents\WindowsPowerShell\profile.ps1 cannot be loaded because running scripts is disabled on
this system. For more information, see about_Execution_Policies at http://go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:3
+ . 'C:\Users\[redacted]\Documents\WindowsPowerShell\profile.ps1'
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess
Loading personal and system profiles took 1354ms.
```

I then go back to the original issue of arguments (`-example`) being too dark.

I've now tried the installation again, here are my steps:

- Download and unpack zip of package
- Open `solarized-datk.reg` to change registry defaults, clicked continue for warnings and so on
- Opened command prompt, run `Update-Link` commandlet on both cmd and powershell shortcuts
- Copied `Set-SolarizedDarkColorDefaults.ps1` and `Set-SolarizedLightColorDefaults.ps1` to `~/Documents/WindowsPowerShell`
- I then create `profile.ps1` in `~/Documents/WindowsPowerShell` and add `. (Join-Path -Path (Split-Path -Parent -Path $PROFILE) -ChildPath $(switch($HOST.UI.RawUI.BackgroundColor.ToString()){'White'{'Set-SolarizedLightColorDefaults.ps1'}'Black'{'Set-SolarizedDarkColorDefaults.ps1'}default{return}}))`
- Re-opened powershell, issue above persists
