### ISSUE TITLE
Running batch scripts by double click still executing with C:\windows\system32 

### ISSUE THREAD

**Issue by rvorderm** [neilpa/cmd-colors-solarized#25]
After running the install and reboot for good measure, if I double click a batch script it still runs with the system default colors. Is there a registry associate I can change for that? Our product relies on a few batch scripts for automation, and well, it's ugly. :)
![image](https://user-images.githubusercontent.com/4483674/27799688-6ff33690-5fd3-11e7-8324-d132f3e08652.png)

**Comment by rbeesley** [comment]
I think this is one of those times where applying the default console color scheme in the registry will help. You can also look under the Console registry key and see if there are other more specific paths which matches.

**Comment by rvorderm** [comment]
I could SWEAR I had done the registry import. However I no longer have access to that computer to test it, and trying it again at home it's working. So... user error? :)
