### ISSUE TITLE
generalize to arbitrary color scheme

### ISSUE THREAD

**Issue by ssehayek** [neilpa/cmd-colors-solarized#26]
Not really an issue, but was wondering if there exists an easy way to generalize this to arbitrary color scheme.

Great work on this project, by the way!

**Comment by ntomallen** [comment]
I'm actually looking at this, and you can change the color codes to any hex value in Update-Link.ps1. I'm still testing it, though. I'm thinking about creating a PR which puts the colors in an external file with descriptions as to what each color effects if that sounds good.
