### ISSUE TITLE
Changing colors for Ubuntu downloaded from Windows 10 Store

### ISSUE THREAD

**Issue by jcfisher** [neilpa/cmd-colors-solarized#39]
This works perfectly for older versions of Ubuntu on Windows, but I can't make it work for the [new version](https://www.microsoft.com/store/productId/9N9TNGVNDL3Q) (Ubuntu 18.04) that you download from the Windows 10 Store.  When you right-click on the app in the start menu, it no longer gives you the option to "open file location".  Is there a way to find the link to update for the new version?  (Sorry in advance if this isn't the appropriate forum for this question.)

**Comment by lzlrd** [comment]
Works for me mate, when using the registry patching method:
![image](https://user-images.githubusercontent.com/24303423/43862425-944e8d86-9b51-11e8-815a-61cecc33917d.png)

**Comment by jcfisher** [comment]
Thanks.  Running the registry patching method as administrator did the trick.  I'll mark this as closed.
