### ISSUE TITLE
Neophyte here...

### ISSUE THREAD

**Issue by trent85** [neilpa/cmd-colors-solarized#47]
I get the following error when attempting to run this script. I'll be starting a degree in programming next year, so I'm basically clueless at this point about how to fix this. I was able to fix a previous error on line 151 by fixing a typo...
![Capture](https://user-images.githubusercontent.com/3770696/100181917-f67d8b80-2ea0-11eb-8bb9-e9358cc2ed63.PNG)

**Comment by rbeesley** [comment]
You didn't actually download Update-Link.ps1. This looks like what you might see if there was a website validation first. I'm not sure how it got as far as like 353, but there shouldn't be anything like SVG in the PS1.
