### ISSUE TITLE
Shortcut colours

### ISSUE THREAD

**Issue by ianchanning** [neilpa/cmd-colors-solarized#6]
These are lovely colours for the command prompt.

However annoyingly (from Windows, nothing to do with these reg files) they don't get copied across to any shortcuts that you create to run the command prompt. I have a '[make me a sandwich](http://xkcd.com/149/)' shortcut that opens the command prompt in admin mode.

I spotted that the command prompt registry keys are just child keys of the main `Console` key.

So for my shortcut that I named 'Make me a sandwich' you just have to edit the specified key in the 
reg file to:

```
[HKEY_CURRENT_USER\Console\Make me a sandwich]
```

![2014-10-29 15_52_28-make me a sandwich properties](https://cloud.githubusercontent.com/assets/233318/4827838/59732d54-5f7b-11e4-8907-73e316fd0029.png)

**Comment by AnneTheAgile** [comment]
@ianchanning , so are you saying that in order to have a proper shortcut to cmd.exe on your desktop, one which runs admin, you had to add the key you list above? I am confused on how adding that key has anything to do with getting it to run solarized light? thank you!

**Comment by neilpa** [comment]
The font, window, etc. settings are embedded in a shortcut link and override the defaults in `HKCU\Console`. What @ianchanning is saying is that a new subkey of `HKCU\Console\<Link-Title>` overrides the embedded settings.
